### ISSUE TITLE
/boot/uboot/dtbs/ file not found on system arm 3.14.41-ti-r63 

### ISSUE THREAD

**Issue by AdamSLevy** [RobertCNelson/rscm#1]
Trying to use this to set up a serial connection with a GPS

Can't get serial to work on BBB and Ubuntu 3.14.41 for the life of me

**Comment by RobertCNelson** [comment]
`rscm` is eol, please use either:

3.14 kernel: https://github.com/RobertCNelson/dtb-rebuilder
4.1 kernel: https://github.com/beagleboard/bb.org-overlays

Regards,
